version: '3.9'

services:
  baum_app:
    container_name: 'baum_test'
    image: baum_test
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=baum
    - POSTGRES_HOST=192.168.10.25
    - POSTGRES_PORT=5432
    build:
      context: ../
      dockerfile: baum.dockerfile
    volumes:
      - ../:/code
    ports:
      - 8888:8888
    networks:
      - baum

networks:
  baum:
    driver: bridge