version: '3.9'

services:
  postgresql:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=baum
    - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - baum
  
networks:
  baum:
    driver: bridge