version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - baum

networks:
  baum:
    driver: bridge